spring:
    output:
        ansi:
            enabled: always
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb://localhost:27017}
            database: ${MONGODB_DATABASE:sephirah}

server:
    port: ${SERVER_PORT:6023}

mvc:
    throw-exception-if-no-handler-found: true
