/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Badge: typeof import('./src/components/common/util/Badge.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChapterSelectDialog: typeof import('./src/components/manga/details/ChapterSelectDialog.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EmptyContentNotice: typeof import('./src/components/common/util/EmptyContentNotice.vue')['default']
    HomeOptionsDropdown: typeof import('./src/components/home/HomeOptionsDropdown.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MangaProviderBadge: typeof import('./src/components/common/provider/MangaProviderBadge.vue')['default']
    MangaProviderStatusCheck: typeof import('./src/components/home/MangaProviderStatusCheck.vue')['default']
    MangaReaderToolbar: typeof import('./src/components/manga/reader/MangaReaderToolbar.vue')['default']
    MangaStatusBadge: typeof import('./src/components/manga/details/MangaStatusBadge.vue')['default']
    MangaTitleCard: typeof import('./src/components/search/MangaTitleCard.vue')['default']
    MaterialIcon: typeof import('./src/components/common/util/MaterialIcon.vue')['default']
    MockRouteWrapper: typeof import('./src/components/common/util/MockRouteWrapper.vue')['default']
    Overlays: typeof import('./src/components/common/overlay/Overlays.vue')['default']
    ProviderBadgeSmall: typeof import('./src/components/home/ProviderBadgeSmall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBarMain: typeof import('./src/components/common/search/SearchBarMain.vue')['default']
    SearchHFilterWarning: typeof import('./src/components/search/SearchHFilterWarning.vue')['default']
    SearchLangaugeSelector: typeof import('./src/components/common/provider/SearchLangaugeSelector.vue')['default']
    SearchMangaList: typeof import('./src/components/search/SearchMangaList.vue')['default']
    SearchProviderList: typeof import('./src/components/home/SearchProviderList.vue')['default']
    Select: typeof import('primevue/select')['default']
    SkeletonBlock: typeof import('./src/components/common/util/SkeletonBlock.vue')['default']
    Spinner: typeof import('./src/components/common/util/Spinner.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TextDivider: typeof import('./src/components/common/util/TextDivider.vue')['default']
    Topnav: typeof import('./src/components/navbar/Topnav.vue')['default']
  }
}
